# command line: main.py recognition -c config/sl/test.yaml --weights epoch1350_model.pt

base_lr: 0.01
batch_size: 24
config: config/sl/test.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 25
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        custom_layout:
            center: 0
            edge: (0, 1), (1, 2), (2, 16), (0, 3), (3, 4), (4, 5), (5, 6), (6, 7),
                (5, 8), (8, 9), (5, 10), (10, 11), (5, 12), (12, 13), (5, 14), (14,
                15), (16, 17), (17, 18), (16, 19), (19, 20), (16, 21), (21, 22), (16,
                23), (23, 24), (16, 25), (25, 26)
            num_node: 27
        layout: custom
        strategy: spatial
    in_channels: 3
    num_class: 2745
nesterov: true
num_epoch: 1400
num_worker: 4
optimizer: Adam
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step: []
test_batch_size: 24
test_feeder_args: {}
train_feeder_args: data_path:/content/drive/My Drive/st-gcn-sl/test/test_data.npy
    label_path:/content/drive/My Drive/st-gcn-sl/test/test_label.pkl
use_gpu: true
weight_decay: 0.0001
weights: epoch1350_model.pt
work_dir: /content/drive/My Drive/st-gcn-sl
