weights: /content/drive/My Drive/st-gcn-sl/st-gcn/epoch1350_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: /content/drive/My Drive/st-gcn-sl/test/test_data.npy
#  label_path: /content/drive/My Drive/st-gcn-sl/test/test_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2745
  edge_importance_weighting: True
  graph_args:
    layout: 'custom'
    strategy: 'spatial'
    custom_layout:
      num_node: 27
      center: 0
      edge: (0, 1), (1, 2), (2, 16), 
            (0, 3), (3, 4), (4, 5),
            (5, 6), (6, 7),
            (5, 8), (8, 9),
            (5, 10), (10, 11),
            (5, 12), (12, 13),
            (5, 14), (14, 15),
            (16, 17), (17, 18),
            (16, 19), (19, 20),
            (16, 21), (21, 22),
            (16, 23), (23, 24),
            (16, 25), (25, 26)

# test 
phase: test
device: 0
test_batch_size: 24