work_dir: ../../../work/st-gcn-sl/asllvd-skeleton-20/2020-05-12-22-45

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: False
  window_size: 60
  data_path: ../../../data/asllvd-skeleton-20/normalized/train_data.npy 
  label_path: ../../../data/asllvd-skeleton-20/normalized/train_label.pkl
test_feeder_args:
  data_path: ../../../data/asllvd-skeleton-20/normalized/test_data.npy
  label_path: ../../../data/asllvd-skeleton-20/normalized/test_label.pkl

log_interval: 25

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 20
  edge_importance_weighting: True
  graph_args:
    layout: 'custom'
    strategy: 'spatial'
    custom_layout:
      num_node: 27
      center: 0
      edge: (0, 1), (1, 2), (2, 16), 
            (0, 3), (3, 4), (4, 5),
            (5, 6), (6, 7),
            (5, 8), (8, 9),
            (5, 10), (10, 11),
            (5, 12), (12, 13),
            (5, 14), (14, 15),
            (16, 17), (17, 18),
            (16, 19), (19, 20),
            (16, 21), (21, 22),
            (16, 23), (23, 24),
            (16, 25), (25, 26)

# training
device: [0]
batch_size: 8
test_batch_size: 8

#optim
optimizer: Adam
base_lr: 0.01
num_epoch: 400
